---
- name: Install wordpress on CentOS 7 
  hosts: 3.80.178.70
  become: true
  become_method: sudo  
  user: centos   
  ignore_errors: yes 
  tasks: 
    - name: Install httpd
      package: 
        name: httpd
        state: latest
      with_items:
        - httpd
        - php
        - mariadb-server
        - mysql
        - elinks
        - php-mysql
        - php-gd 
      

    - name: Download wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz 
        dest: /tmp/

    - name: Extract
      anarchive: 
        src: /tmp/wordpress_version tar.gz
        dest: /var/www/html/
        

    - name: move files
      shell: "mv /var/www/html/wordpress/*  /var/www/html/"
      

    - name: Move index.html 
      shell: "mv /var/www/html/index.html /tmp/"
      

    - name: run apache 
      systemd: 
        name: httpd 
        state: restarted 
        enabled: yes 
      

    - name: Add User
      user: 
        name: bob
        state: present
        


    - name: Add User
      user: 
        name: ben
        state: present
        


    - name: Add User
      user: 
        name: lisa
        state: present
        


    - name: add user 
      user:
        user: katty
        state: present
        


 


    



     