---
- name: My Firsts playbook
  hosts: all
  become: true
  become_method: sudo
  user: centos
  tasks:
  - name: Install package
    package:
      name: httpd
      state: installed


  - name: Add bob
    user:
      name: httpd
      state: present   




 
        